[project]
name = "aoi-defect-history"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autopep8>=2.3.2",
    "black>=25.9.0",
    "ktec-smt-schedule",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "requests>=2.32.5",
    "yapf>=0.43.0",
]

[tool.uv.sources]
ktec-smt-schedule = { path = "../ktec_smt_schedule" }
