[project]
name = "aoi-defect-history"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autopep8>=2.3.2",
    "black>=25.9.0",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "yapf>=0.43.0",
]
