name: Build Windows Executables (with spec file)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, x86]
        include:
          - architecture: x64
            python-arch: x64
            output-name: aoi-defect-history-win64
          - architecture: x86
            python-arch: x86
            output-name: aoi-defect-history-win32

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        architecture: ${{ matrix.python-arch }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync
        uv pip install pyinstaller

    - name: Debug environment
      run: |
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Python version: $(python --version)"
        Write-Host "PyInstaller version: $(uv run pyinstaller --version)"
        Write-Host "Files in current directory:"
        Get-ChildItem -Name
      shell: pwsh

    - name: Build executable with spec file
      run: |
        uv run pyinstaller pyinstaller.spec
      continue-on-error: false

    - name: Rename executable to match architecture
      run: |
        $files = Get-ChildItem -Path "dist" -Filter "aoi-defect-history-*.exe"
        if ($files.Count -gt 0) {
          $originalName = $files[0].Name
          $newName = "${{ matrix.output-name }}.exe"
          Rename-Item -Path "dist\$originalName" -NewName $newName
          Write-Host "Renamed $originalName to $newName"
        } else {
          Write-Host "No executable found in dist directory"
          exit 1
        }
      shell: pwsh

    - name: Test executable exists
      run: |
        if (Test-Path "dist\${{ matrix.output-name }}.exe") {
          Write-Host "Executable built successfully"
          Get-Item "dist\${{ matrix.output-name }}.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "Error: Executable not found"
          exit 1
        }
      shell: pwsh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output-name }}
        path: dist/${{ matrix.output-name }}.exe
        retention-days: 30

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/aoi-defect-history-win64/aoi-defect-history-win64.exe
          ./artifacts/aoi-defect-history-win32/aoi-defect-history-win32.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}